using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Resto.Plugin.Hotel
{
    public partial class HotelPluginAgeGroups : UserControl
    {
        public HotelPluginAgeGroups()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            hotelAgeGroupsTableAdapter1.Fill(restoDataSet1.HotelAgeGroups);
        }
    }
}
