//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Plugin.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoomType
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int max_capacity { get; set; }
        public Nullable<int> max_capacity_adult { get; set; }
        public Nullable<int> max_capacity_children { get; set; }
    }
}
