//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Plugin.Hotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestoEntitiesRoom : DbContext
    {
        public RestoEntitiesRoom()
          : base(ConnectionStringBuilder.Construct("HotelRoom"))
        {
            //Disable initializer
            Database.SetInitializer<RestoEntitiesRoom>(null);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HotelRoom>().ToTable("HotelRoom");
        }
       

        public virtual DbSet<HotelRoom> HotelRoom { get; set; }
    }
}
