//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Plugin.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom
    {
        public System.Guid id { get; set; }
        public string number { get; set; }
        public System.Guid status_id { get; set; }
        public bool smoke { get; set; }
        public System.Guid room_type_id { get; set; }
        public int floor { get; set; }
    }
}
